# Generated by Django 5.1.6 on 2026-04-23 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('operations', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('vehicle', 'Vehicle'), ('secondary', 'Secondary')], max_length=20)),
                ('status', models.CharField(default='open', max_length=30)),
                ('manual_entry', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weighing_sessions', to='parties.collectioncenter')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weighing_sessions', to='devices.device')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weighing_sessions', to='operations.purchaseoperation')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weighing_sessions', to='parties.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScaleReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_type', models.CharField(choices=[('gross', 'Gross'), ('tare', 'Tare'), ('direct', 'Direct'), ('manual', 'Manual'), ('contingency', 'Contingency')], max_length=20)),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tare_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=120)),
                ('is_stable', models.BooleanField(default=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scale_readings', to='devices.device')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='weighing.weighingsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
