# Generated by Django 5.2.13 on 2026-04-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=30),
        ),
    ]
