# Generated by Django 5.1.6 on 2026-04-23 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('materials', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='materials.material'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='operations.purchaseoperation'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='ticket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='operations.ticketitem'),
        ),
    ]
