# Generated by Django 5.1.6 on 2026-04-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialization', '0001_initial'),
        ('inventory', '0002_initial'),
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='commercialization.saleitem'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='commercialization.saleorder'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='operations.purchaseoperation'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='ticket_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='operations.ticketitem'),
        ),
    ]
