# Generated by Django 5.1.6 on 2026-05-12 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymovement_sale_item_and_more'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='processing.materialprocess'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='process_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='processing.materialprocessinput'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='process_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='processing.materialprocessoutput'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='process_waste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='processing.materialprocesswaste'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='source_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('adjustment', 'Adjustment'), ('purchase_in', 'Compra ingresada'), ('process_input_out', 'Consumo por proceso'), ('process_output_in', 'Salida procesada'), ('process_waste_out', 'Merma de proceso'), ('sale_out', 'Venta'), ('manual_adjustment_in', 'Ajuste positivo'), ('manual_adjustment_out', 'Ajuste negativo'), ('transfer_in', 'Transferencia recibida'), ('transfer_out', 'Transferencia enviada')], default='inbound', max_length=32),
        ),
    ]
