# Generated by Django 5.1.6 on 2026-04-23 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_routes', to='parties.collectioncenter')),
                ('origin_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_routes', to='parties.collectioncenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
