# Generated by Django 5.1.6 on 2026-04-23 06:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_at', models.DateTimeField(auto_now_add=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_distance_km', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('odometer_start', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('geo_start_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_start_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_end_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_end_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('destination_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_collection_trips', to='parties.collectioncenter')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_trips', to='parties.driver')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_trips', to=settings.AUTH_USER_MODEL)),
                ('origin_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_collection_trips', to='parties.collectioncenter')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_trips', to='logistics.route')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_trips', to='parties.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
