# Generated by Django 5.1.6 on 2026-04-24 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_collectiontrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='trip_stops/')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logistics.collectiontrip')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
    ]
