# Generated by Django 5.1.6 on 2026-04-24 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_collectiontripstop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontrip',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectiontrip',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_collection_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectiontrip',
            name='closure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collectiontrip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='CollectionTripIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='trip_incidents/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_trip_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_trip_incidents', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='logistics.collectiontrip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
