# Generated by Django 5.1.6 on 2026-04-24 02:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_collectiontrip_closed_at_collectiontrip_closed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontrip',
            name='estimated_fuel_liters',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='collectiontrip',
            name='last_telemetry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectiontrip',
            name='last_telemetry_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='collectiontrip',
            name='last_telemetry_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='collectiontrip',
            name='telemetry_distance_km',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='collectiontrip',
            name='telemetry_points_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CollectionTripTelemetryPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('source', models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual')], default='gps', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_points', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='logistics.collectiontrip')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
    ]
