# Generated by Django 5.1.6 on 2026-04-23 05:53

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('registered', 'Registered'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('print_status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('reprinted', 'Reprinted')], default='pending', max_length=20)),
                ('source', models.CharField(default='purchase', max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('total_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total_merma_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('vehicle_differential', 'Vehicle Differential'), ('secondary_direct', 'Secondary Direct'), ('manual_contingency', 'Manual Contingency')], max_length=40)),
                ('gross_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('tare_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('net_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('merma_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('void', 'Void')], default='pending', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
