# Generated by Django 5.1.6 on 2026-04-23 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('materials', '0001_initial'),
        ('operations', '0001_initial'),
        ('parties', '0001_initial'),
        ('weighing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoperation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseoperation',
            name='collection_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_operations', to='parties.collectioncenter'),
        ),
        migrations.AddField(
            model_name='purchaseoperation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_operations', to='parties.personorcompany'),
        ),
        migrations.AddField(
            model_name='purchaseoperation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_operations', to='parties.driver'),
        ),
        migrations.AddField(
            model_name='purchaseoperation',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseoperation',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_operations', to='logistics.route'),
        ),
        migrations.AddField(
            model_name='purchaseoperation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_operations', to='parties.vehicle'),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ticket_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_items', to='materials.material'),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.purchaseoperation'),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='scale_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_items', to='weighing.scalereading'),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='weighing_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_items', to='weighing.weighingsession'),
        ),
    ]
