# Generated by Django 5.2.13 on 2026-04-26 04:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12),
        ),
    ]
