# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_cashier_closure_authorization"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseoperation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
