# Generated by Django 5.1.6 on 2026-04-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='expected_km_per_liter',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=8),
        ),
    ]
