# Generated by Django 5.1.6 on 2026-05-12 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0005_material_is_buyable_material_is_processable_and_more'),
        ('parties', '0003_collectioncenter_kind_collectioncenter_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(db_index=True, max_length=50, unique=True)),
                ('process_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_material_processes', to=settings.AUTH_USER_MODEL)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_processes', to='parties.collectioncenter')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_material_processes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_material_processes', to=settings.AUTH_USER_MODEL)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_processes', to='processing.processtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProcessInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('source_inventory_reference', models.CharField(blank=True, max_length=120)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_inputs', to='materials.material')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='processing.materialprocess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProcessOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_outputs', to='materials.material')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='processing.materialprocess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProcessWaste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_type', models.CharField(choices=[('merma', 'Merma'), ('waste', 'Desperdicio'), ('loss', 'Pérdida')], default='merma', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_wastes', to='materials.material')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='processing.materialprocess')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
