# Generated by Django 5.1.6 on 2026-04-23 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('evidence', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custodyevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custodyevent',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='operations.purchaseoperation'),
        ),
        migrations.AddField(
            model_name='custodyevent',
            name='ticket_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to='operations.ticketitem'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='custody_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='evidence.custodyevent'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='operations.purchaseoperation'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='ticket_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='operations.ticketitem'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printlog',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='operations.purchaseoperation'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printlog',
            name='printer_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_logs', to='devices.device'),
        ),
    ]
