# Generated by Django 5.1.6 on 2026-04-23 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_initial'),
        ('logistics', '0002_collectiontrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_files', to='logistics.collectiontrip'),
        ),
    ]
