# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercialization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="list_unit_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="lot_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="presentation",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="price_override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="quality",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="buyer_type_snapshot",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="contract_reference",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="destination_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="negotiated_price_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="payment_terms",
            field=models.CharField(choices=[("cash", "Contado"), ("credit", "Crédito"), ("advance", "Anticipo"), ("transfer", "Transferencia"), ("mixed", "Pago mixto")], default="cash", max_length=20),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="sale_type",
            field=models.CharField(choices=[("direct_weight", "Venta directa por peso"), ("lot", "Venta por lote"), ("shipment", "Venta por carga"), ("negotiated", "Precio negociado"), ("credit", "Venta a crédito"), ("processed", "Material procesado"), ("mixed", "Venta mixta"), ("contract", "Contrato o convenio")], default="direct_weight", max_length=30),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="transport_mode",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="transport_operator",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="transport_plates",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="status",
            field=models.CharField(choices=[("draft", "Borrador"), ("confirmed", "Confirmada"), ("loading", "En carga"), ("completed", "Entregada"), ("paid", "Pagada"), ("credit", "Crédito"), ("cancelled", "Cancelada"), ("adjusted", "Ajustada")], default="draft", max_length=20),
        ),
    ]
