# Generated by Django 5.2.13 on 2026-04-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercialization", "0002_saleitem_list_unit_price_saleitem_lot_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("confirmed", "Confirmada"),
                    ("sent_to_cashier", "Enviada a caja"),
                    ("scheduled_delivery", "Entrega programada"),
                    ("loading", "En carga"),
                    ("in_route", "En ruta"),
                    ("delivered", "Entregada"),
                    ("completed", "Entregada"),
                    ("paid", "Pagada"),
                    ("credit", "Crédito"),
                    ("closed", "Cerrada"),
                    ("cancelled", "Cancelada"),
                    ("adjusted", "Ajustada"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
