# Generated by Django 5.1.6 on 2026-05-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_pricelist_unique_party_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_buyable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_processable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='is_sellable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='subfamily',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
