# Generated by Django 5.1.6 on 2026-04-23 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('identifier', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('vehicle_scale', 'Vehicle Scale'), ('secondary_scale', 'Secondary Scale'), ('thermal_printer', 'Thermal Printer')], max_length=50)),
                ('port', models.CharField(blank=True, max_length=120)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_stable', models.BooleanField(default=True)),
                ('is_manual_fallback', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('collection_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='parties.collectioncenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
