# Generated by Django 5.2.13 on 2026-04-29 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("parties", "0003_collectioncenter_kind_collectioncenter_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="vehicle",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="gps_devices", to="parties.vehicle"),
        ),
        migrations.AlterField(
            model_name="device",
            name="kind",
            field=models.CharField(
                choices=[
                    ("vehicle_scale", "Vehicle Scale"),
                    ("secondary_scale", "Secondary Scale"),
                    ("thermal_printer", "Thermal Printer"),
                    ("gps_tracker", "GPS Tracker"),
                ],
                max_length=50,
            ),
        ),
    ]
